---
- name: Download WordPress
  command: curl -o /var/www/wordpress.tar.gz https://ja.wordpress.org/wordpress-4.7.2-ja.tar.gz

- name: Extract archive
  command: /bin/tar xvf /var/www/wordpress.tar.gz -C /var/www/

- name: database for wordpress is created
  mysql_db: db={{ wp_db_name }} state=present encoding=utf8

- name:  wordpress database user is created
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL state=present host={{ wp_web_server }}

- name: wordpress is configured
  copy: src=wp-config.php dest=/var/www/wordpress/wp-config.php

## wordpressアカウント
## admin / admin
- name: wordpress is configured
  copy: src=wordpress.sql dest=/tmp/wordpress.sql

- name: mysql_restore
  mysql_db: name={{ wp_db_user }} target=/tmp/wordpress.sql state=import

- name: dump_delete
  file: path=/tmp/wordpress.sql state=absent
